### ISSUE TITLE
Hooks are not passed merged context

### ISSUE THREAD

**Issue by toddbaert** [open-feature/java-sdk#1047]
We are correctly passing the merged context to the flag evaluation as outlined in [3.2.3](https://openfeature.dev/specification/sections/evaluation-context#requirement-323), however, we are not passing that context to the hooks themselves.

Solution:

The before hooks should be passed a merge of `API (global) > Transaction > Client > Invocation` and the resulting returned context from the hooks should then be passed to the evaluation and all subsequent hooks.

Steps: 

- fix as described
- tests which fail before the fix, and pass after

Here's equivalent code in the JS implementation: https://github.com/open-feature/js-sdk/blob/cb4e56ae803ffe15dd4367b73d82315ce5d053a8/packages/server/src/client/internal/open-feature-client.ts#L248-L268

**Comment by UtkarshSharma2612** [comment]
Can I work on this issue?

**Comment by toddbaert** [comment]
> Can I work on this issue?

Hey @UtkarshSharma2612 ! Sure - but it's a significant issue with a relatively high priority to fix. I was going to start on it today, but if you think it's possible that you can complete it by next week, I will assign it to you. If that is too rushed, I can help you find some other issue or you can help with review.

**Comment by UtkarshSharma2612** [comment]
Hey @toddbaert I am relatively new to open source contribution and I am not sure I will be able to complete by next week it will be a bit rushed and not justified for a high priority issue. Can you help me find another issue, I am willing to help with review and other issues for sure 😄

**Comment by toddbaert** [comment]
@UtkarshSharma2612 [here](https://github.com/open-feature/java-sdk-contrib/issues/901) is another pretty clean-cut issue that you can work on. It's also Java. Take a look!
