### ISSUE TITLE
Add JMH Benchmarks for the critical code paths

### ISSUE THREAD

**Issue by aepfli** [open-feature/java-sdk#1146]
Our tool is excellent, but more and more people are using it. We already received internal information, that some code paths tend to be hotspots, especially `structure` operations.

Evaluating this without a proper test harness around it is hard; hence, it might be a good idea to add a JMH Suite to our tests for verification and to allow us to spot hotspots earlier in the future.

- https://github.com/openjdk/jmh
- https://www.baeldung.com/java-microbenchmark-harness

**Comment by toddbaert** [comment]
Yes this is a great idea. We could run these as part of the SDK CI.

We may also want to add something similar to the [contribs](https://github.com/open-feature/java-sdk-contrib) eventually, though there it will be up to each component owner what constitutes adequate performance.

**Comment by toddbaert** [comment]
I'm not sure if https://github.com/open-feature/java-sdk/pull/1156 fully resolves this, but it's certainly related.

@aepfli I'm happy to add a check that will check we don't have regressions with this number, but it will involve a bit of a hacky script.

**Comment by aepfli** [comment]
Do you think we can close this as https://github.com/open-feature/java-sdk/pull/1156 is merged, or do you want to invest further in it? If yes, we should maybe adapt the ticket description to add more context and concrete to-dos.

**Comment by aepfli** [comment]
i think with https://github.com/open-feature/java-sdk/pull/1182 and https://github.com/open-feature/java-sdk/pull/1178 this can be closed now
