### ISSUE TITLE
Remove spot-bug dependency if it is possible.

### ISSUE THREAD

**Issue by pbhandari9541** [open-feature/java-sdk#171]
Spot bug dependency is creating an issue on our clients during deployment.
the dependency is flowing as below: 
 openfeature-sdk -->ep-commons->ep-adaptor-> client

if we could remove from the root itself, then the downstream don't need to exclude from the client.

**Comment by beeme1mr** [comment]
@justinabrahms @toddbaert is something we can do?

**Comment by pbhandari9541** [comment]
yes, this is already merged : https://github.com/open-feature/java-sdk/pull/173
