### ISSUE TITLE
api extension discussion

### ISSUE THREAD

**Issue by pbhandari9541** [open-feature/java-sdk#203]
**Issue:**
Sone Customer wants more information from api like following without featureFlag. 
1. API for listing qualified Variant Id, name etc  for a given user/site/channel
2. API for providing list of qualified feature flag for a giver user/site/channel.
3. API for Multiple feature flag qualification like batch.(Currently, we support use cases for a single feature flag evaluation.)
4. .
5. .

The above list are some of them. we can shortlist them. 

**Thoughts:** 
It would have been great if open-feature have this kind of capability..
like: String[] OR MutableStructure getQualifiedFlags(EvaluationContext); return list of feature flag names for a given usr etc.
provider checks required input for evaluation in EvaluationContext , perform qualification and list all qualified flags for a given BU( filter unnecessary data).

**what's next??**
1.is there a plans to extend open-feature api's to support above request? Currently, we have api that only works with feature flag and default value at minimum?
2. is open-feature extensible to customer needs?

Notes:
if open-feature doesn't  plans to provide these interfaces. Then, we may have to plan for other solution to fulfill their needs.

**Comment by thomaspoignant** [comment]
Hey @pbhandari9541 this could be a discussion to open in the ofep repo https://github.com/open-feature/ofep since it is linked to more than the java sdk.
