### ISSUE TITLE
Value.isList accepts List<Object> where only the first element is a Value

### ISSUE THREAD

**Issue by javicv** [open-feature/java-sdk#286]
https://github.com/open-feature/java-sdk/blob/ed2e963a2a1eb59be7fa19e3a4cd1a0791c354e3/src/main/java/dev/openfeature/sdk/Value.java#L133-L137

This method `isList()` is used in constructor https://github.com/open-feature/java-sdk/blob/ed2e963a2a1eb59be7fa19e3a4cd1a0791c354e3/src/main/java/dev/openfeature/sdk/Value.java#L37 but it's checking only the first element of the list. With this check a `List<Object>` can be added if only the first element is a `Value` while the other aren't.

In my opinion this test must pass, but it fails because the exception isn't thrown
```java
@Test
public void listMustContainOnlyValues() {
    String item = "item";
    List<Object> list = new ArrayList<>();
    list.add(new Value(item));
    list.add(item);
    try {
        new Value((Object) list);
        fail("Should fail because list contains values and non-values and the exception should be thrown.");
    } catch (InstantiationException e) {
        assertEquals("Invalid value type: class java.util.ArrayList", e.getMessage());
    }
}
```
Maybe the constructor with `Object` parameter shouldn't accept lists to force the use of constructor with `List<Value>` where the list will only contain elements of type `Value` https://github.com/open-feature/java-sdk/blob/ed2e963a2a1eb59be7fa19e3a4cd1a0791c354e3/src/main/java/dev/openfeature/sdk/Value.java#L75-L77

**Comment by Kavindu-Dodan** [comment]
@javicv  PR is ready for review - https://github.com/open-feature/java-sdk/pull/350 

@toddbaert  @justinabrahms  hope you can review :)

**Comment by toddbaert** [comment]
[This](https://github.com/open-feature/java-sdk/pull/350/files#r1144817603) is my concern.
