### ISSUE TITLE
Get float value?

### ISSUE THREAD

**Issue by toddbaert** [open-feature/java-sdk#32]
It seems like the Java SDK doesn't support floats. Is that something that should be supported? I suppose this can be worked around with strings, but I wonder if decimal values are important enough to be supported, especially fractional values like .5 could be practical.

Relevant part of the spec: https://github.com/open-feature/spec/blob/main/specification/types.md#number

**Comment by justinabrahms** [comment]
I'm not clear on how to handle this one. I wonder if we could just deal with `Number`s and defer it to the caller? https://docs.oracle.com/javase/8/docs/api/java/lang/Number.html

**Comment by toddbaert** [comment]
> I'm not clear on how to handle this one. I wonder if we could just deal with Numbers and defer it to the caller? https://docs.oracle.com/javase/8/docs/api/java/lang/Number.html

I think that's a fine solution, personally.

Paging @agentgonzo, interested in your take on this one.

**Comment by thomaspoignant** [comment]
I have open #34 to fix this.
