### ISSUE TITLE
[Question] Why there is no something like EnvironmentVariablesProvider?

### ISSUE THREAD

**Issue by madhead** [open-feature/java-sdk#339]
Although using the OpenFeature to read values from the environment instead of a simple `System.getenv()` may be an overkill, why there is no such a Provider implementation anyway?

**Comment by beeme1mr** [comment]
Awesome, thank you. I'll try and review your pr by Monday at the latest.

Do you mind if I close this issue?

**Comment by madhead** [comment]
No, no objections :)
