### ISSUE TITLE
[Question] Readme text: Is it correct?

### ISSUE THREAD

**Issue by agardnerIT** [open-feature/java-sdk#361]
The readme states: "We support multiple data types for flags (numbers, strings, booleans, objects) as well as hooks, which can alter the lifecycle of a flag evaluation."

That doesn't read right to me... Is it?

**Comment by Kavindu-Dodan** [comment]
This refers to flag evaluation result type & hooks, which are defined through OpenFeature specification. See below extractions for reference, 

Flag evaluation [1]

`The client can be used to do basic flag evaluation, which simply returns flag values of a particular type. The default value must also be specified`

Hooks [2]

`Hooks are a mechanism that allow for the addition of arbitrary behavior at well-defined points of the flag evaluation life-cycle. Use cases include validation of the resolved flag value, modifying or adding data to the evaluation context, logging, telemetry, and tracking

Hope this helps to clarify your doubt. 

[1] - https://docs.openfeature.dev/docs/reference/concepts/evaluation-api#flag-evaluation
[2] - https://docs.openfeature.dev/docs/reference/concepts/hooks/

**Comment by agardnerIT** [comment]
Oh! I misread it. I read it as "multiple data types which can alter the lifecycle of a flag evaluation". My bad. Makes sense now :)
