### ISSUE TITLE
The SDK Jar does not provide a Module Name 

### ISSUE THREAD

**Issue by ARobertsCollibra** [open-feature/java-sdk#362]
This is a major issue for developers using both IntelliJ and Gradle due to a [Gradle bug](https://github.com/gradle/gradle/issues/17609)

But even when that bug is not present having the automatically created module name be plain `sdk` is not very descriptive and has a high potential for confusion.

This can be fixed without requiring Java 9 or higher by adding `Automatic-Module-Name` to the `MANIFEST.MF` in the published Jar.  Alternatively, the project can be updated to compile to Java 11 bytecode and be fully modularized.  Currently the contributing guidelines say `Java 11+` but the pom.xml say `1.8`.

**Comment by toddbaert** [comment]
>This can be fixed without requiring Java 9 or higher by adding Automatic-Module-Name to the MANIFEST.MF in the published Jar. 

@ARobertsCollibra thanks for bringing this up. I'm ashamed to say I had made a mental note do do exactly this and forgot.

> Currently the contributing guidelines say Java 11+ but the pom.xml say 1.8.

> Alternatively, the project can be updated to compile to Java 11 bytecode and be fully modularized. Currently the contributing guidelines say Java 11+ but the pom.xml say 1.8.

Good catch, the guidlelines should be updated. We do indeed want to stay with Java8 for now for maximum compatibility, but at some point it makes sense to migrate to 11+ and properly modularize the library. cc @justinabrahms

**Comment by toddbaert** [comment]
I've created [this](https://github.com/open-feature/java-sdk-contrib/issues/261) in contrib (cc @justinabrahms @Kavindu-Dodan @thiyagu06 )

**Comment by toddbaert** [comment]
@ARobertsCollibra the fix should available in [1.3.1](https://central.sonatype.com/artifact/dev.openfeature/sdk/1.3.1). If you find time, please confirm.

**Comment by ARobertsCollibra** [comment]
The problem appears to have been resolved!
Thank you!
