### ISSUE TITLE
Java 8+ support and modules

### ISSUE THREAD

**Issue by Kavindu-Dodan** [open-feature/java-sdk#369]
**Background** 

The current SDK is versioned for java 8. And moving to a newer version shows benefits. This issue is to discuss the need and potential to migrate to a newer LTS version.

Potential candidate version - Java 11

**Discussion**

A considerable amount of interest is still there for java 8 as many major organizations are still in the process of migrating or sticking to older versions for legacy code bases. There is also mixed feedback about the benefits of using java modules [1] so using modules might not be the only driver for such a decision. However, to make the SDK robust with new language features and future-proof, it could be in its best interest to de-support and move to a newer version of Java.

[1] - https://stackoverflow.com/questions/62950667/is-there-any-need-to-switch-to-modules-when-migrating-to-java-9-or-later

**Comment by toddbaert** [comment]
I agree with your points. I think that modules alone is not enough of a justification to migrate to 9, but if we DO migrate to 9, there's not really a downside to supporting modules. As your link says:

> If you maintain a library then I strongly recommend that you upgrade it to be a module if you haven’t done so already, and if all of your library’s dependencies have been converted.

I'd like to understand how many consumers are still using 8. I think you're right and it's still very widely used.

**Comment by toddbaert** [comment]
For reference: https://endoflife.date/java

**Comment by Kavindu-Dodan** [comment]
> I think that modules alone is not enough of a justification to migrate to 9, but if we DO migrate to 9, there's not really a downside to supporting modules

Yes. Introducing modules benefits projects which utilize modules. But it doesn't affect projects that will not introduce modules [1]. Because of this reason, I also think it is best to adopt modules when we migrate. 

[1] - https://openjdk.org/projects/jigsaw/spec/sotms/#automatic-modules

**Comment by justinabrahms** [comment]
As much as I'd love the language features, eBay is/was on Java 8 and uses this in production, so I think I'd like to wait until the majority of their work was on java > 8. I think other enterprise-y places are in a similar boat.

Does anyone know if maven offers metrics on this sort of thing?

**Comment by thomaspoignant** [comment]
I agree with @toddbaert I know a lot of companies that are still on java8 and don't migrate because it is a heavy load on their side, so I will not migrate to a higher version for now.

**Comment by toddbaert** [comment]
> Does anyone know if maven offers metrics on this sort of thing?

I briefly tried to find some "live" metrics, but the best I found was a survey by Perforce/JRebel from 2022 which claims:

>Asked which JDK (Java Development Kit) programming language was being used in their main application, 37% of respondents in the Perforce-sponsored survey answered Java 8.

So ya... A lot still on 8. I think for now we should stay here. Things like the `automatic module name` which came up recently allow us to support newer runtimes well for the time being.

**Comment by Kavindu-Dodan** [comment]
Thank you @justinabrahms & @thomaspoignant for the quick feedback. 

I came across this interesting statistics page from JetBrains [1]. It has some interesting insights especially for library devs and given that this comes from an IDE developer, the stats should be valid. And to quote highlights,

> For many years, Java 8 has remained the leading Java version. However, its usage dropped by 12 percentage points in 2022. This is not surprising because in March 2022, Java 8 lost its Oracle Premier Support. Thus, many developers decided to migrate their applications to different versions. The emergence of Java 17, a new long-term support version, attracted a lot of users. Also, other versions like Java 11 and Java 16 have gained greater audiences.

Anyway, I also agree with @toddbaert  that we must defer this discussion to later. Hence, will close this specific issue and let's revisit this topic later.

[1] - https://www.jetbrains.com/lp/devecosystem-2022/java/
