### ISSUE TITLE
Impossible to get all attributes from the EvaluationContext

### ISSUE THREAD

**Issue by thomaspoignant** [open-feature/java-sdk#39]
It is not possible to get all the attributes from the `EvaluationContext`.
My use-case is when we want to convert the `EvaluationContext` into the format expected by the vendor we will need to build a new object based on the actual `EvaluationContext`.

For now, the only way to get the information in the context is by knowing the field's name, which makes it impossible to get all the fields at once.
In addition of `getStructureAttribute`, `getStringAttribute`, `getIntegerAttribute`, `getBooleanAttribute` I would suggest to have a method like this:

```java
public Map<String,Object> getAttributes() {
   // ...
}
```

**Comment by justinabrahms** [comment]
Fixed with https://github.com/open-feature/java-sdk/pull/41
