### ISSUE TITLE
Changes to support spec `v0.6.0` compliance

### ISSUE THREAD

**Issue by toddbaert** [open-feature/java-sdk#437]
## Implement specification v0.6.0 changes

See [changes since last release](https://github.com/open-feature/spec/compare/v0.5.2...v0.6.0).

Please note there's no need to complete all these tasks in a single PR (in fact, that's not recommended).

### Functional requirements:

- [x] implement flag metadata: https://github.com/open-feature/spec/commit/74c373e089ad77bf8cac84f3d93c00c945ff3a8a
- [x] #442
- [x] #449 : https://github.com/open-feature/spec/commit/a4ffec3d4416b8ad6d12d1ebfa2faf81ad153f65
- [x] #440
  - the spec is intentionally loose here to allow for an implementation that feels "java-ish", consider:
    - [java.util.EventListener](https://docs.oracle.com/javase/8/docs/api/java/util/EventListener.html) and its subclasses
    - a custom interface
    - other options?

### Non-functional requirements:

- [x] add relevant tests
- [x] add examples and documentation, see template README
- [x] update specification badge to `v0.6.0`: [![Specification](https://img.shields.io/static/v1?label=Specification&message=v0.6.0&color=yellow)](https://github.com/open-feature/spec/tree/v0.6.0)

### Keep in mind:

- backwards compatibility is _highly encouraged_
  - take every precaution to ensure existing code written by _application authors_ and existing providers implementations, do not break
- it's recommended these features are released together

**Comment by toddbaert** [comment]
named client support was implemented by @justinabrahms

**Comment by toddbaert** [comment]
I'm interested in taking on the events part of this. I'm going to open a new issue specifically about that if nobody objects.

**Comment by Kavindu-Dodan** [comment]
I am actively working on metadata requirement and will open a PR soon for the review

**Comment by toddbaert** [comment]
Done with https://github.com/open-feature/java-sdk/pull/364
