### ISSUE TITLE
In-memory provider for e2e testing and minimal SDK usage

### ISSUE THREAD

**Issue by Kavindu-Dodan** [open-feature/java-sdk#523]
As proposed by **OFEP: SDK end-to-end test strategy** [^1], we should create an in-memory provider for Java-sdk

We already have contributions for Python[^2] & Go [^3], and we can use same flag format, constructors & error handling strategy for this implementation.

- [x] Implement the in-memory provider
- [x] Migrate existing e2e tests[^4] to newly create in-memory provider 
  - search repo for `https://github.com/open-feature/java-sdk/issues/523` for related TODOs. 

[^1]: https://github.com/open-feature/ofep/pull/71
[^2]: https://github.com/open-feature/python-sdk/pull/157
[^3]: https://github.com/open-feature/go-sdk/pull/192
[^4]: https://github.com/open-feature/java-sdk/tree/main/src/test/java/dev/openfeature/sdk/e2e

**Comment by toddbaert** [comment]
Small related PR here: https://github.com/open-feature/java-sdk/pull/543

**Comment by liran2000** [comment]
@Kavindu-Dodan @toddbaert as PR merged, can be resolved ?

**Comment by Kavindu-Dodan** [comment]
@liran2000 yes, this is complete. Thank you for working on this 🙌
