### ISSUE TITLE
Shallow map or deep map?

### ISSUE THREAD

**Issue by justinabrahms** [open-feature/java-sdk#53]
https://github.com/open-feature/java-sdk/pull/51#discussion_r955642085

Should the Structure object map be shallow or deep copies?

**Comment by kinyoklion** [comment]
In the use case I hypothesize for this I think that shallow copies make sense. That use case being the transcription of an EvaluationContext into a different provider specific object.

If we did deep copies then structures contained inside other structures would get deep copied multiple times depending on their depth. Any intermediate copies would only be used to deep copy themselves again when `asMap` was called on them.

So, for that use case, I prefer the shallow copy.

**Comment by s-sen** [comment]
IMO shallow copy is fine, but If the intent is to return a view of the map then Collections.unModifiableMap can be used. But I am not sure if I am being paranoid here!

**Comment by toddbaert** [comment]
I think I like the idea of using `Collections.unModifiableMap`.

**Comment by agentgonzo** [comment]
AFAIR, `Collections.unModifiableMap` will only help you by protecting the top-level map.
But `Structure` can be nested, eg, a Structure could be (pseudocode)
```
Structure mystruct = {
  topKey: new Structure({
    innerKey: new Value("innerValue")
  })
}
```

If you were to use `unMofifiableMap`, then it would protect you from doing things like `mystruct.add(...)` or any mutation operations, but you could still do `mystruct.get("topKey").add("whatever", "stuff")` or `mystruct.get("topKey").remove("innerKey")`
