### ISSUE TITLE
[BUG] aftershutDown lambda on set provider is not working as expected.

### ISSUE THREAD

**Issue by thiyagu06** [open-feature/java-sdk#577]
I see couple of issues on `afterShutdown` parameter passed in the setProvider method.

1.  when updating the named/default provider using the `setProvider` method, shutdown lambda of old provider should be called. We should maintain the shutdownBehaviour of the actual provider and use when actually shutting the provider down.

2. `afterShutdown` lambda is never called when FeatureProvider.shutdown() is get called explicitly. (at the end of application life cycle).?

https://github.com/open-feature/java-sdk/blob/main/src/main/java/dev/openfeature/sdk/ProviderRepository.java#L111C42-L111C55

```
            @Test
            @DisplayName("should call shutdown consumer of old provider when provider is updating the provider")
            void shouldCallShutDowOfTheOldProviderWhenUpdatingTheProvider() {
                FeatureProvider oldProvider = createMockedProvider();
                FeatureProvider newProvider = createMockedProvider();
                Consumer<FeatureProvider> oldShutDownBehaviour = mock(Consumer.class);
                Consumer<FeatureProvider> newShutDownBehaviour = mock(Consumer.class);
                providerRepository.setProvider(oldProvider, mockAfterSet(), mockAfterInit(), oldShutDownBehaviour, mockAfterError());
                waitForSettingProviderHasBeenCompleted(ProviderRepository::getProvider, oldProvider);
                providerRepository.setProvider(newProvider, mockAfterSet(), mockAfterInit(), newShutDownBehaviour,
                        mockAfterError());
                waitForSettingProviderHasBeenCompleted(ProviderRepository::getProvider, newProvider);
                verify(oldProvider, timeout(TIMEOUT)).shutdown();
                //shut down behavior passed when setting the new provider is called on oldProvider.
                verify(newShutDownBehaviour, times(1)).accept(oldProvider);
                // shut down behavior passed when setting the old provider should be called.
                verify(oldShutDownBehaviour, times(1)).accept(oldProvider);
            }
```
```
           @Test
            @DisplayName("should call afterShutdown when provider shutdown method is called")
            void shouldCallShutDownLambda() {
                FeatureProvider oldProvider = createMockedProvider();
                Consumer<FeatureProvider> oldShutDownBehaviour = mock(Consumer.class);
                providerRepository.setProvider(oldProvider, mockAfterSet(), mockAfterInit(), oldShutDownBehaviour, mockAfterError());
                waitForSettingProviderHasBeenCompleted(ProviderRepository::getProvider, oldProvider);
                oldProvider.shutdown();
                verify(oldShutDownBehaviour, times(1)).accept(oldProvider);
            }
```

**Comment by beeme1mr** [comment]
@Kavindu-Dodan could you look into this when you have a moment?

**Comment by Kavindu-Dodan** [comment]
@thiyagu06 thank you for raising your concerns,

1. We perform a shutdown invocation for the old provider [^1]. This invoke old provider's shutdown method as well as remove event handling registration 

2. There's a provider repository and eventing cleanup [^2], which invoke provider shutdown internally 

I think we have covered your points, but I might be missing something you intended to question. Could you please check the referenced codes and let us know ? 

[1^]: https://github.com/open-feature/java-sdk/blob/main/src/main/java/dev/openfeature/sdk/ProviderRepository.java#L137-L140
[^2]: https://github.com/open-feature/java-sdk/blob/main/src/main/java/dev/openfeature/sdk/OpenFeatureAPI.java#L235-L241

**Comment by thiyagu06** [comment]
Hi @Kavindu-Dodan, 

my bad. I overlooked the `setProvider` method in `ProviderRepository` class 🤦‍♂️ . You're right we're detaching the events handler of the shutdown method only.  Thanks for your time. I will close this issue.
