### ISSUE TITLE
Double vs Integer fields in `Structure`

### ISSUE THREAD

**Issue by toddbaert** [open-feature/java-sdk#58]
IMO the changes in https://github.com/open-feature/java-sdk/pull/51 have been working well, but the one potential issue I'd like to bring up is the differentiation between ints/doubles.

From an application authors perspective, a `Value` can be attempted to be resolved to an int/double with `Value.asInteger()` and `Value.asDouble()` respectively. This works well, in that context the author likely knows how to interpret the numeric value. However, when a provider is constructing the structure, it must do either `new Value(int)` or `new Value(double)`, and when parsing JSON, XML or protobuf, etc, the provider might not really know which choice to make.

I think we have a few options:

- Remove all int-related parts of the the Structure API. Use Doubles for everything (e.g. `Value.asInteger()` and `new Value(int)` would be removed.
- Maintain `new Value(int)` and `new Value(double)`, but store all numbers as doubles. `Value.asDouble()` and `Value.asInteger()` will return the appropriate representation of this number. `Value.isDouble()` and `Value.isInteger()` will be consolidated as `Value.isNumber()`.
- something else?

@kinyoklion @justinabrahms @beeme1mr @agentgonzo @rgrassian-split

**Comment by toddbaert** [comment]
> You could also store it however it was provided, but still provide that same interface (isNumber, asInt, asDouble). The only advantage I see is, if the provider does know the type, then you could get integers larger than 2^53-1 for providers that did have that capability. (Not endorsing this option, just pointing it out as an option. I like doubles for the storage.)

I had this thought too, I'm glad you brought it up. I the the precision/overflow issues are probably enough of an edge case that we need not to worry about them and can just store double, but let's see what others think. Whatever we decide here, I'll implement similar behavior in https://github.com/open-feature/dotnet-sdk/pull/53

**Comment by toddbaert** [comment]
@justinabrahms Do you have a take on this one? I can easily implement either in the java-sdk, it will likely be a breaking change, but minor.

**Comment by justinabrahms** [comment]
You can do this in the main SDK. cc @s-sen

**Comment by toddbaert** [comment]
> You can do this in the main SDK. cc @s-sen

What @kinyoklion suggests of the 2 options? Just want to be sure!

**Comment by justinabrahms** [comment]
Implementor's choice on how you store the data, but logically we want a Number type which can resolve as either a double or integer depending on what the application author needs.

**Comment by toddbaert** [comment]
https://github.com/open-feature/java-sdk/pull/61
