### ISSUE TITLE
Update readme examples to include setProviderAndWait

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/java-sdk#592]
The SDK has support for `setProviderAndWait` since 1.6.0. It was added in [this PR](https://github.com/open-feature/java-sdk/pull/563). Update the README examples to show how it can be used.

```[tasklist]
### Tasks
- [ ] Update the example in the quick start section
- [ ] Expand the provider's section to show both the async and synchronous options.
```

**Comment by kumarankit999** [comment]
hey @beeme1mr , Can i work on it

**Comment by beeme1mr** [comment]
Sure

**Comment by code4Y** [comment]
Hi @beeme1mr 
I've been actively working on this issue and have already prepared the necessary changes. I realize it was my mistake not to mention my involvement here and request assignment earlier.

@kumarankit999, if you haven't started working on this issue yet, I kindly request to take it over. My changes are ready and incorporated into a PR.

Thank you for your understanding and consideration.
