### ISSUE TITLE
Conform to spec `v0.7.0`

### ISSUE THREAD

**Issue by toddbaert** [open-feature/java-sdk#599]
Update the SDK to be compliant with `v0.7.0`.

- [ ] ensure compliance with all point in `v0.7.0` (see [here](https://github.com/open-feature/spec/releases/tag/v0.7.0) for complete list of changes) 
  - [ ] event handlers should run immediately if the associated provider is in the state associated with that handler already
  - [ ] add new STALE provider state
  - [ ] add `provider name` to `event details`
  - [ ] update test descriptions/numbers (use: `python spec_finder.py`, see CONTRIBUTING.md)
- [ ] implement relevant tests
- [ ] update spec badge in README.md

**Comment by MeenuyD** [comment]
Hello @toddbaert I would like to work on this issue can you please guide how to get started

**Comment by toddbaert** [comment]
> Hello @toddbaert I would like to work on this issue can you please guide how to get started

You can perhaps look at [my similar changes in the js-sdk](https://github.com/open-feature/js-sdk/pull/541) - but he description basically contains all the required behavioral changes.

**Comment by toddbaert** [comment]
I'll get started on this. @MeenuyD I will add you to the review.
