### ISSUE TITLE
[vuln] SNYK-JAVA-COMMONSCODEC-561518

### ISSUE THREAD

**Issue by toddbaert** [open-feature/java-sdk#60]
Users are seeing https://security.snyk.io/vuln/SNYK-JAVA-COMMONSCODEC-561518 on installation.

**Comment by justinabrahms** [comment]
Not showing in snyk. https://app.snyk.io/org/open-feature/project/141e62d0-6a3b-4010-b5f6-ee554e6cafc5

**Comment by justinabrahms** [comment]
This is probably just bumping spotbugs to 4.7.2 https://github.com/spotbugs/spotbugs/releases/tag/4.7.2

**Comment by toddbaert** [comment]
This is resolved.
