### ISSUE TITLE
test against a real flagd setup

### ISSUE THREAD

**Issue by justinabrahms** [open-feature/java-sdk#62]
We should have a pre-release check which will spin up a flagd provider and run some java code to validate that the thing actually works. I don't know if this is quick enough to be part of the PR flow (ideal), but it should at least happen before we release new versions.

**Comment by justinabrahms** [comment]
cc @toddbaert

**Comment by toddbaert** [comment]
I will take this one (though likely I won't get to it until next week). 

I will implement something like what I researched [here](https://github.com/open-feature/node-sdk/pull/70), centralizing as much as possible.

**Comment by toddbaert** [comment]
Resolved with https://github.com/open-feature/java-sdk/pull/77
