### ISSUE TITLE
traversing structure kinda sucks?

### ISSUE THREAD

**Issue by justinabrahms** [open-feature/java-sdk#72]
This is what the structure API looks like in one of our internal tests. I think we might want to add some convenience APIs for traversal. Granted, it's some nested json.. but still.

<img width="821" alt="image" src="https://user-images.githubusercontent.com/3853/190218178-07944b7a-9e73-423e-b9db-ba9c86287c81.png">

**Comment by justinabrahms** [comment]
Talking with folks internally (@s-sen, ejan, ganga, pramesh).. they're saying:

"We're going to tell developers to only use structures if they want a simple map"

"If you want a complex object, you should probably store it as a string and convert it to your pojo directly (using something like gson)"

**Comment by toddbaert** [comment]
> "We're going to tell developers to only use structures if they want a simple map"

Ya, I think that is basically the expected use case. If you want to automatically hydrate classes I think that's probably better handled as you say, with some custom parsing. You can use whatever JSON API to do that.

I'd note that what you have above is pretty similar many "dumb" JSON APIs, as well as protobuf APIs and some feature flag SDKs that support JSON objects (LaunchDarkly, for example).
