### ISSUE TITLE
Change package name?

### ISSUE THREAD

**Issue by toddbaert** [open-feature/java-sdk#82]
On the Sept 29 community call, an attendee suggested we remove "java" from the package names in the SDK (their argument was "java" is implied). I see their point, though I also don't think it's needed.

Basically: `dev.openfeature.javasdk` would become: `dev.openfeature.sdk`.

I'm just bringing this up because "now is the time" before we start marking things as stable. Mostly interested in @justinabrahms 's opinion on this one.

**UPDATE: We will likely do this at 1.0**

**Comment by toddbaert** [comment]
A thought: if we published a kotlin sdk... would we also call it dev.openfeature.sdk? And would that be a problem? Might it cause classpath collisions?

**Comment by justinabrahms** [comment]
I'm okay with making this change as part of a 1.0 release but not sooner.

**Comment by toddbaert** [comment]
> I'm okay with making this change as part of a 1.0 release but not sooner.

Sounds good to me!

**Comment by justinabrahms** [comment]
@toddbaert @s-sen tells me that we should make the change now b/c it will be easier than 2 weeks from now (there's an internal release). I think they're the main customer of the javasdk at this point, so I'm inclined to ship this now. I may push this change if you don't beat me to it first.
