### ISSUE TITLE
CONTRIBUTING.md doesn't have accurate steps

### ISSUE THREAD

**Issue by ARobertsCollibra** [open-feature/java-sdk#858]
CONTRIBUTING.md says 

> Any contributions you make are expected to be tested with unit tests. You can validate these work with `gradle test`, or the automation itself will run them for you when you make a PR.

But the repo is setup as a Maven build not a Gradle build, so there are no valid steps that describe how to prepare for a valid PR

**Comment by Kavindu-Dodan** [comment]
Thank you @ARobertsCollibra , I am improving this wirth https://github.com/open-feature/java-sdk/pull/863
