### ISSUE TITLE
[FEATURE] API Ergonomics

### ISSUE THREAD

**Issue by jhollanderpax8** [open-feature/java-sdk#940]
The Java API is pretty verbose when compared to some of the other language SDKs.

```typescript
await OpenFeature.setContext({ myUserData: 'myUserValue' });
const boolValue = await client.getBooleanValue('boolFlag', false);
```

Versus Java:

```java
OpenFeatureAPI api = OpenFeatureAPI.getInstance();
Map<String, Value> transactionAttrs = new HashMap<>();
transactionAttrs.put("userId", new Value("userId"));
EvaluationContext transactionCtx = new ImmutableContext(transactionAttrs);
api.setTransactionContext(apiCtx);

api.client.getBooleanValue("my-flag", false, api.getEvaluationContext)
```

I'm aware of language differences and Java's propensity for verbosity but it just doesn't seem necessary.

I've written some simple extension functions in my Kotlin projects to make this API so much more friendly and I don't think it sacrifices any of the principles that the API is trying to enforce around EvaluationContext and Value, it just makes them less prominent in the API itself.  

Why can we not have an API like:

```java
OpenFeatureAPI api = OpenFeatureAPI.getInstance();
api.setTransactionContext(Map.of("userId", "userId");

api.client.getBooleanValue("my-flag", false)
```

The constructor for `Value` takes in an `Object` anyway so why not just allow passing in a `Map<String, Object>`?   The internal workings can create the EvalutationContext and Values from the HashMap and enforce the "type safety" of Value.   

It feels like the API is forcing the developer to deal with the internal implementation details of the Provider API.

**Comment by Kavindu-Dodan** [comment]
@jhollanderpax8 I think you are confusing yourself with two concepts, API level context [^1] and context propagation [^2]

Regarding ergonomics of API level context setting, you can already do a one line initialization like below, 

```java
OpenFeatureAPI api = OpenFeatureAPI.getInstance();
api.setEvaluationContext(new ImmutableContext(Map.of("foo", new Value("Bar"))));
```

Here the `EvaluationContext` implementation is important as we expose a getter from API `api.getEvaluationContext()` so the setter can decide on immutability. 

Transaction context on the other hand accepts an implementation of `TransactionContextPropagator` where the default is a no-op implementation. There's a built-in implementation for a thread local propagator. 

[^1]: https://openfeature.dev/specification/sections/evaluation-context/#conditional-requirement-3211
[^2]: https://openfeature.dev/specification/sections/evaluation-context/#33-context-propagation

**Comment by Kavindu-Dodan** [comment]
@toddbaert fyi, I think we can improve our code documentation to improve the clarity of our API docs. Currently, they only have `{@inheritDoc}` annotations [^1]

[^1]: - https://github.com/open-feature/java-sdk/blob/v1.8.0/src/main/java/dev/openfeature/sdk/OpenFeatureAPI.java#L81-L107

**Comment by jhollanderpax8** [comment]
@Kavindu-Dodan Thank you for the response.  Maybe my example doesn't really cut it as it's not so much about lines of code.  My primary lense for this is something like log4j MDC context or OTEL Span annotations, which I think are reasonably good APIs for progressively building request context across a number of different stages of an HTTP request lifecycle.

With the Evaluation Context API it's really awkward to do what `MDC.put` can do:

Maybe in my Spring Auth Handler I want to do something like:
```
   MDC.put("user.id", auth.getPrinciple().getId());
```

and then in the my controller I want to do:

```
   MDC.put("product.id", request.productId);
```

This is awkward to do with the current API:

```
api.setTransactionContext(api.getCurrentContext().merge(new ImmutableContext("user.id", auth.getPrinciple.getId())
```

and then later:

```
api.setTransactionContext(api.getCurrentContext().merge(new ImmutableContext("product.id", request.productId)
```

Maybe I'm just not connecting the dots from what the documentation shows to a more efficient and correct way to do it.  Maybe there is just a need for a bit more detail and clarity in the docs and I'm just being a bit obtuse about it.   Apologies if I've accidentally treated Issues system as a QA forum.  I just felt that my struggles were an indicator of a missing piece.

**Comment by Kavindu-Dodan** [comment]
I think I understand your issue. Unfortunately, I don't think there's a nice solution when dealing with `ImmutableContext`. As the name suggests, it is immutable. However, you can use `MutableContext`, which can be mutated.

```java
MutableContext mutableCtx = new MutableContext(Map.of("k1", new Value("v1")));
OpenFeatureAPI api = OpenFeatureAPI.getInstance();
api.setEvaluationContext(mutableCtx)

// mutate context on-demand
this.mutableCtx.add("key", "value");
```

An alternative you can check is to use different context levels. For example, in the example below, I am using API (global) context, client context and the evaluation context, 

```java
// API level context
OpenFeatureAPI api = OpenFeatureAPI.getInstance();
api.setEvaluationContext(new ImmutableContext(Map.of("k1", new Value("v1"))));

// Client level context - in a different package/file where you need an OpenFeature client
final Client client = api.getClient();
client.setEvaluationContext(new ImmutableContext(Map.of("k2", new Value("v2"))));

// Flag evaluation context
client.getBooleanDetails("flagKey", false, new ImmutableContext(Map.of("k3", new Value("v3"))));
```
When evaluating the flag, the merged context will contain all context keys as they are unique. I think given your examples with product id, user id, you should prefer to use the second approach where you can inject context data to the evaluation or to a client.

**Comment by jhollanderpax8** [comment]
Thank you @Kavindu-Dodan I think both answers give some clarity.  

I missed the connection between the Java SDK docs and the main OpenFeature docs for this: https://openfeature.dev/docs/reference/concepts/evaluation-context/#dynamic-context-implementations-server-side-sdks

I still think there is awkwardness but I can see now that it is likely a result of the cross platform and multi-provider nature of this system.  There is complexity there that is beyond just a "nicer" Java SDK API.  

Thanks for your responses and, again, apologies for blurring the line between an Issue and what could probably have been a Slack convo.
